Repository operate-first/toolbox, pull requests merged in 2021-08, with the labels that each got.

#42 Add OPA binary and allow tests to be more configurable
  Dockerfile
  scripts/test-conftest
  scripts/test-kustomize-build
Labels: approved, size/S, lgtm

#41 feat: Add make, nodejs, prow binaries and bump to fedora 34
  Dockerfile
  README.md
Labels: approved, lgtm

#47 feat: Add pre-commit
  Dockerfile
  README.md
Labels: approved, size/S, lgtm

#48 feat: Add opfcli
  Dockerfile
  README.md
Labels: approved, size/XS, lgtm

#40 Adding mini CLI script for cloning repos
  scripts/o1-clone
Labels: approved, size/M, lgtm
