Repository operate-first/toolbox, pull requests merged in 2021-06, with the labels that each got.

#32 fix: Speed up kustomize build by checking overlays only
  scripts/test-kustomize-build
Labels: approved, lgtm, size/XS

#33 feat: Release v0.3.6
  README.md
Labels: approved, lgtm, size/XS

#34 chore: cleanup owners
  OWNERS
Labels: approved, lgtm, size/XS

#35 chore: Set up CI to release
  .aicoe-ci.yaml
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  .thoth.yaml
  version.py
Labels: approved, lgtm, size/L

#36 feat: Make test-kustomiz-build test changes only
  scripts/test-kustomize-build
Labels: approved, lgtm, size/S

#39 Update version in readme
  README.md
Labels: approved, lgtm, size/XS
